spring:
  application:
    name: classroom-class
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/store}
    username: ${DATABASE_USERNAME:store}
    password: ${DATABASE_PASSWORD:store123321}
    driver-class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true
    schemas: aula
  jpa:
    properties:
      hibernate:
        default_schema: aula
management:
  endpoints:
    web:
      base-path: /aulas/actuator
      exposure:
        include: [ 'prometheus' ]

eureka: 
  client:
    reguster-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}


