apiVersion: v1
kind: Service
metadata:
    name: classroom
    labels:
        name: classroom
spec:
    type: NodePort
    ports:
        - port: 8080
          targetPort: 8080
          protocol: TCP
    selector:
        app: classroom